# Generated by Django 3.0.6 on 2020-05-23 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GirlFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='You',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='TaiKhoan',
        ),
        migrations.AddField(
            model_name='girlfriend',
            name='boyfriend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.You'),
        ),
    ]
