# Generated by Django 3.0.6 on 2020-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200523_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girlfriend',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='you',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
