# Generated by Django 3.0.6 on 2020-05-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200523_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sp', models.CharField(default=True, max_length=200, verbose_name='Mã sp')),
                ('ten_sp', models.CharField(default=True, max_length=200, verbose_name='Tên sp')),
                ('gia', models.CharField(default=True, max_length=200, verbose_name='Giá')),
            ],
            options={
                'verbose_name': 'Sản Phẩm',
                'verbose_name_plural': 'Sản Phẩm',
            },
        ),
        migrations.CreateModel(
            name='NhaSanXuat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên')),
            ],
            options={
                'verbose_name': 'Nhà Sản Xuất',
                'verbose_name_plural': 'Nhà Sản Xuất',
            },
        ),
        migrations.DeleteModel(
            name='GirlFriend',
        ),
        migrations.DeleteModel(
            name='You',
        ),
        migrations.AddField(
            model_name='mathang',
            name='nhasanxuat',
            field=models.ManyToManyField(to='myapp.NhaSanXuat'),
        ),
    ]
